wandb:
  entity: 'babycar27'
  project: 'curman'


data:
  inp: 'category_id'
  out: 'bbox'

model:
  txt_in_len: 10 #300
  txt_out_len: 15 #300
  seed: 2
  model_name: 'google/flan-t5-base'
  pretrained_model: 'google/flan-t5-base'

ppo_trainer:
  config:
    steps: 51200
    learning_rate: 0.0000141
    remove_unused_columns: false
    log_with: 'wandb'
    batch_size: 1

text_generation:
  parameters:
    top_k: -1
    top_p: 1.0
    do_sample: true
    eos_token_id: -1
   # max_new_tokens: 15

