wandb:
  entity: 'babycar27'
  project: 'curman'

data:
  inp: 'category_id'
  out: 'bbox'

model:
  txt_in_len: 5
  txt_out_len: 5
  seed: 2
  model_name: 'gpt2-large'
  pretrained_model: 'gpt2-large'

ppo_trainer:
  config:
    steps: 51200
    learning_rate: 0.0000141
    remove_unused_columns: false
    log_with: 'wandb'
    batch_size: 1

text_generation:
  parameters:
    min_length: -1
    top_k: 0.0
    top_p: 1.0
    do_sample: true
    eos_token_id: -1
    max_new_tokens: 5

